[package]
name = "verilogae_ffi"
version = "0.9.0-beta8"
authors = ["DSPOM"]
edition = "2021"
license = "GPL-3.0"

links = "verilogae"

[lib]
doctest = false


[dependencies]

verilogae = { version = "0.9.0-beta8", path = "../verilogae", optional=true}

[dev-dependencies]

sourcegen = {version = "0.0.0", path="../sourcegen"}
xshell = "0.2"

[features]
default = ["static"]
static = ["verilogae"]



