[package]
name = "melange"
version = "0.0.0"
authors = ["DSPOM"]
edition = "2021"
license="GPL-3.0"


[lib]
doctest = false

[dependencies]
termcolor = "1.1"
ahash = "0.7"
anyhow = "1"
stdx = {version="0.0.0", path="../stdx"}
typed_indexmap = {version="0.0.0", path="../typed_indexmap"}
typed-index-collections = "3.0"
camino = "1.1.1"
indexmap = "1.6"
lasso = {version = "0.6", features = ["ahash"]}
klu-rs = "0.3.0"
num-complex  = "0.4.2"

basedb = { version = "0.0.0", path = "../basedb" }
sim_back = { version = "0.0.0", path = "../sim_back" }
osdi = { version = "0.0.0", path = "../osdi" }

llvm = { version = "0.0.0", path = "../llvm" }
mir_llvm = { version = "0.0.0", path = "../mir_llvm" }
target = { version = "0.0.0", path = "../target" }
linker = { version = "0.0.0", path = "../linker" }

base_n = {version = "1", path = "../../lib/base_n"}
paths = {version = "0.0", path = "../paths"}

md5 = "0.7"
directories-next = "2"
path-absolutize = "3.0.13"
text-size = "1.1"
libc = "0.2"
libloading = "0.7"
log="0.4.17"
cli-table = "0.4.7"
pretty_dtoa = "0.3.0"
bitflags = "1.3.2"