[package]
name = "sim_back"
version = "0.0.0"
authors = ["DSPOM"]
edition = "2021"
license = "GPL-3.0"

[lib]
doctest = false

[dependencies]

stdx = { version = "0.0.0", path = "../stdx" }
typed_indexmap = {version = "0.0.0", path = "../typed_indexmap"}
bitset = {version = "0.0.0", path = "../bitset"}
paths = {version = "0.0", path = "../paths"}

syntax = {version = "0.0.0", path = "../syntax"}
basedb = { version = "0.0.0", path = "../basedb" }
hir_def = { version = "0.0.0", path = "../hir_def" }
hir_lower = {version ="0.0.0", path ="../hir_lower"}
hir_ty = { version = "0.0.0", path = "../hir_ty" }

mir = { version = "0.0.0", path = "../mir" }
mir_autodiff = { version = "0.0.0", path = "../mir_autodiff" }
mir_opt = { version = "0.0.0", path = "../mir_opt" }
workqueue = {version = "0.0.0", path = "../workqueue" }

typed-index-collections = "3.0"
ahash = "0.7"
lasso = {version = "0.6", features = ["ahash"]}
parking_lot = "0.12"

anyhow = "1"

salsa = "0.17.0-pre.2"
indexmap = "1.6"
smol_str = {version = "0.1.23", default_features=false}

# rayon-core = "1"


[dev-dependencies]


sourcegen = {version ="0.0.0", path ="../sourcegen"}
proc-macro2 = "1.0"
quote = "1.0"


expect-test = "1.1"

mir_interpret = {version = "0.0.0", path = "../mir_interpret" }
float-cmp =  "0.9"


